# Generated by Django 5.2.4 on 2025-07-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='color',
        ),
        migrations.AddField(
            model_name='child',
            name='colour',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
