# Generated by Django 5.2.4 on 2025-08-01 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_remove_child_color_child_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(blank=True, choices=[('None', 'None'), ('Homework', 'Homework'), ('Health', 'Health'), ('School', 'School'), ('Activities', 'Activities'), ('Chores', 'Chores'), ('Appointments', 'Appointments'), ('Reminders', 'Reminders'), ('Celebrations', 'Celebrations'), ('Achievements', 'Achievements'), ('Other', 'Other')], default='None', on_delete=django.db.models.deletion.CASCADE, to='planner.category'),
        ),
    ]
