# Generated by Django 5.2.4 on 2025-08-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_entry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='colour',
            field=models.CharField(blank=True, choices=[('#FF6B6B', 'Coral Red'), ('#4ECDC4', 'Turquoise'), ('#0D6A80', 'Sky Blue'), ('#96CEB4', 'Mint Green'), ('#D1D811', 'Sunny Yellow'), ('#DDA0DD', 'Plum Purple'), ('#AD6A0D', 'Peach Orange'), ('#8516EE', 'Light Blue'), ('#0CEB0C', 'Pale Green'), ('#BE12E0', 'Bright Pink')], default='#FF6B6B', max_length=7),
        ),
    ]
