# Generated by Django 5.2.4 on 2025-08-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_entry_category_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('note', 'Note'), ('task', 'Task'), ('event', 'Event')], default='note', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
