# Generated by Django 5.2.4 on 2025-08-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_alter_entry_entry_type_alter_entry_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='event_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='event_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
