# Generated by Django 5.2.4 on 2025-08-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_add_separate_event_date_time_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='task_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='task_due_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
