# Generated by Django 5.2.4 on 2025-08-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_entry_task_due_date_entry_task_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('task', 'Task'), ('event', 'Event')], default='task', max_length=10),
        ),
    ]
