# Generated by Django 5.2.4 on 2025-08-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_alter_entry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('note', 'Note'), ('task', 'Task'), ('event', 'Event')], default='note', max_length=10),
        ),
    ]
